language: ruby
rvm:
  - 3.1.6
  - 3.2.4
  - 3.3.5
  - truffleruby
install:
  - bundle install --jobs=3 --retry=3
services:
  - redis-server
cache:
  - bundler
env:
  - REDIS_PORT=6379
script:
  - bundle exec rspec
notifications:
  email:
    on_success: change
    on_failure: change
